model:
  provider: ollama
  name: qwen2.5:3b # llama3.2:1b 
  base_url: http://localhost:11434

chunker:
  strategy: fixed_size
  chunk_size: 1000
  overlap: 100

generation:
  question_type: short_answer
  difficulty: medium
  num_questions: 3